### ISSUE TITLE
api.uigf.org/dict/en.json已过期

### ISSUE THREAD

**Issue by IDwrong** [Masterain98/Paimon.moe-WishHistory-UIGF-Exporter#1]

**Comment by Masterain98** [comment]
fixed at UIGF-Org/UIGF-API@546eac63241e893778da62e8af24557883fd02e2

[en-us.json.zip](https://github.com/Masterain98/Paimon.moe-WishHistory-UIGF-Exporter/files/10079727/en-us.zip)
